### ISSUE TITLE
atomos.multiprocessing.atomic.AtomicReference not working properly

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/atomos#3]
It seems that memory is not being shared between processes as expected.

Here's a simple test case:

```diff
diff --git a/tests/test_multiprocessing_atomic.py b/tests/test_multiprocessing_atomic.py
index f8600b4..9548b2c 100644
--- a/tests/test_multiprocessing_atomic.py
+++ b/tests/test_multiprocessing_atomic.py
@@ -79,3 +79,26 @@ def test_concurrent_atomic_int(process_count=10, loop_count=1000):
         p.join()
 
     assert atomic_int.get() == process_count * loop_count
+
+
+def test_concurrent_atomic_ref(process_count=10, loop_count=1000):
+    atomic_ref = atomos.multiprocessing.atomic.AtomicReference(0)
+
+    def inc_atomic_ref():
+        for _ in range(loop_count):
+            while True:
+                oldval = atomic_ref.get()
+                is_set = atomic_ref.compare_and_set(oldval, oldval + 1)
+                if is_set:
+                    break
+
+    processes = []
+    for _ in range(process_count):
+        p = Process(target=inc_atomic_ref)
+        processes.append(p)
+        p.start()
+
+    for p in processes:
+        p.join()
+
+    assert atomic_ref.get() == process_count * loop_count
```

The `atomic_ref` ends up returning `0` so it seems that memory between processes is not being shared as we'd expect.

**Comment by wiliamsouza** [comment]
I created a branch[1] with the tests to reproduce the bug. I seems that `atomos.atomic.AtomicReference` not works with `multiprocessing.Process`.

[1] https://github.com/maxcountryman/atomos/compare/master...wiliamsouza:bug/atomic_reference

**Comment by maxcountryman** [comment]
I think that multiprocessing copies an object into a process but does not allow that process to write to the original object in memory. To support shared objects, it provides a Manager system.

**Comment by maxcountryman** [comment]
All right, I think I may not have provided the best test case. However I've got a patch which I hope generally solves the issue (it was partly me making a mistake I specifically warned against in the documentation and partly the thing I mentioned before about multiprocessing and shared memory).
